package prueba;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of alumno.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Alumno implements Serializable {


	
	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Codalumno. */
	private Integer codalumno;

	/** Nombrealumno. */
	private String nombrealumno;

	/** Direccion. */
	private String direccion;

	/** Localidad. */
	private String localidad;

	/** The set of notas. */
	private Set<Notas> notasSet;

	/**
	 * Constructor.
	 */
	public Alumno() {
		System.out.println("Bienvenido");
		this.notasSet = new HashSet<Notas>();
	}
	/**
	 * Set the Codalumno.
	 * 
	 * @param codalumno
	 *            Codalumno
	 */
	public void setCodalumno(Integer codalumno) {
		this.codalumno = codalumno;
	}

	/**
	 * Get the Codalumno.
	 * 
	 * @return Codalumno
	 */
	public Integer getCodalumno() {
		return this.codalumno;
	}

	/**
	 * Set the Nombrealumno.
	 * 
	 * @param nombrealumno
	 *            Nombrealumno
	 */
	public void setNombrealumno(String nombrealumno) {
		this.nombrealumno = nombrealumno;
	}

	/**
	 * Get the Nombrealumno.
	 * 
	 * @return Nombrealumno
	 */
	public String getNombrealumno() {
		return this.nombrealumno;
	}

	/**
	 * Set the Direccion.
	 * 
	 * @param direccion
	 *            Direccion
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * Get the Direccion.
	 * 
	 * @return Direccion
	 */
	public String getDireccion() {
		return this.direccion;
	}

	/**
	 * Set the Localidad.
	 * 
	 * @param localidad
	 *            Localidad
	 */
	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	/**
	 * Get the Localidad.
	 * 
	 * @return Localidad
	 */
	public String getLocalidad() {
		return this.localidad;
	}

	/**
	 * Set the set of the notas.
	 * 
	 * @param notasSet
	 *            The set of notas
	 */
	public void setNotasSet(Set<Notas> notasSet) {
		this.notasSet = notasSet;
	}

	/**
	 * Add the notas.
	 * 
	 * @param notas
	 *            notas
	 */
	public void addNotas(Notas notas) {
		this.notasSet.add(notas);
	}

	/**
	 * Get the set of the notas.
	 * 
	 * @return The set of notas
	 */
	public Set<Notas> getNotasSet() {
		return this.notasSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codalumno == null) ? 0 : codalumno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Alumno other = (Alumno) obj;
		if (codalumno == null) {
			if (other.codalumno != null) {
				return false;
			}
		} else if (!codalumno.equals(other.codalumno)) {
			return false;
		}
		return true;
	}

}
