package prueba;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of departamentos.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Departamentos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** dept_no. */
	private Integer deptNo;

	/** dnombre. */
	private String dnombre;

	/** loc. */
	private String loc;

	/** The set of empleados. */
	private Set<Empleados> empleadosSet;

	/**
	 * Constructor.
	 */
	public Departamentos() {
		this.empleadosSet = new HashSet<Empleados>();
	}

	/**
	 * Set the dept_no.
	 * 
	 * @param deptNo
	 *            dept_no
	 */
	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	/**
	 * Get the dept_no.
	 * 
	 * @return dept_no
	 */
	public Integer getDeptNo() {
		return this.deptNo;
	}

	/**
	 * Set the dnombre.
	 * 
	 * @param dnombre
	 *            dnombre
	 */
	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	/**
	 * Get the dnombre.
	 * 
	 * @return dnombre
	 */
	public String getDnombre() {
		return this.dnombre;
	}

	/**
	 * Set the loc.
	 * 
	 * @param loc
	 *            loc
	 */
	public void setLoc(String loc) {
		this.loc = loc;
	}

	/**
	 * Get the loc.
	 * 
	 * @return loc
	 */
	public String getLoc() {
		return this.loc;
	}

	/**
	 * Set the set of the empleados.
	 * 
	 * @param empleadosSet
	 *            The set of empleados
	 */
	public void setEmpleadosSet(Set<Empleados> empleadosSet) {
		this.empleadosSet = empleadosSet;
	}

	/**
	 * Add the empleados.
	 * 
	 * @param empleados
	 *            empleados
	 */
	public void addEmpleados(Empleados empleados) {
		this.empleadosSet.add(empleados);
	}

	/**
	 * Get the set of the empleados.
	 * 
	 * @return The set of empleados
	 */
	public Set<Empleados> getEmpleadosSet() {
		return this.empleadosSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((deptNo == null) ? 0 : deptNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Departamentos other = (Departamentos) obj;
		if (deptNo == null) {
			if (other.deptNo != null) {
				return false;
			}
		} else if (!deptNo.equals(other.deptNo)) {
			return false;
		}
		return true;
	}

}
