package prueba;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of empleados.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Empleados implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** emp_no. */
	private Integer empNo;

	/** apellido. */
	private String apellido;

	/** oficio. */
	private String oficio;

	/** dir. */
	private Integer dir;

	/** fecha_alt. */
	private Date fechaAlt;

	/** salario. */
	private Float salario;

	/** comision. */
	private Float comision;

	/** departamentos. */
	private Departamentos departamentos;

	/**
	 * Constructor.
	 */
	public Empleados() {
	}

	/**
	 * Set the emp_no.
	 * 
	 * @param empNo
	 *            emp_no
	 */
	public void setEmpNo(Integer empNo) {
		this.empNo = empNo;
	}

	/**
	 * Get the emp_no.
	 * 
	 * @return emp_no
	 */
	public Integer getEmpNo() {
		return this.empNo;
	}

	/**
	 * Set the apellido.
	 * 
	 * @param apellido
	 *            apellido
	 */
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	/**
	 * Get the apellido.
	 * 
	 * @return apellido
	 */
	public String getApellido() {
		return this.apellido;
	}

	/**
	 * Set the oficio.
	 * 
	 * @param oficio
	 *            oficio
	 */
	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	/**
	 * Get the oficio.
	 * 
	 * @return oficio
	 */
	public String getOficio() {
		return this.oficio;
	}

	/**
	 * Set the dir.
	 * 
	 * @param dir
	 *            dir
	 */
	public void setDir(Integer dir) {
		this.dir = dir;
	}

	/**
	 * Get the dir.
	 * 
	 * @return dir
	 */
	public Integer getDir() {
		return this.dir;
	}

	/**
	 * Set the fecha_alt.
	 * 
	 * @param fechaAlt
	 *            fecha_alt
	 */
	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	/**
	 * Get the fecha_alt.
	 * 
	 * @return fecha_alt
	 */
	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	/**
	 * Set the salario.
	 * 
	 * @param salario
	 *            salario
	 */
	public void setSalario(Float salario) {
		this.salario = salario;
	}

	/**
	 * Get the salario.
	 * 
	 * @return salario
	 */
	public Float getSalario() {
		return this.salario;
	}

	/**
	 * Set the comision.
	 * 
	 * @param comision
	 *            comision
	 */
	public void setComision(Float comision) {
		this.comision = comision;
	}

	/**
	 * Get the comision.
	 * 
	 * @return comision
	 */
	public Float getComision() {
		return this.comision;
	}

	/**
	 * Set the departamentos.
	 * 
	 * @param departamentos
	 *            departamentos
	 */
	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	/**
	 * Get the departamentos.
	 * 
	 * @return departamentos
	 */
	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empNo == null) ? 0 : empNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Empleados other = (Empleados) obj;
		if (empNo == null) {
			if (other.empNo != null) {
				return false;
			}
		} else if (!empNo.equals(other.empNo)) {
			return false;
		}
		return true;
	}

}
