package prueba;

import java.io.Serializable;

/**
 * Model class of notas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Notas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** idnota. */
	private Integer idnota;

	/** alumno. */
	private Alumno alumno;

	/** nombreasig. */
	private String nombreasig;

	/** nota. */
	private Float nota;

	/**
	 * Constructor.
	 */
	public Notas() {
	}

	/**
	 * Set the idnota.
	 * 
	 * @param idnota
	 *            idnota
	 */
	public void setIdnota(Integer idnota) {
		this.idnota = idnota;
	}

	/**
	 * Get the idnota.
	 * 
	 * @return idnota
	 */
	public Integer getIdnota() {
		return this.idnota;
	}

	/**
	 * Set the alumno.
	 * 
	 * @param alumno
	 *            alumno
	 */
	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	/**
	 * Get the alumno.
	 * 
	 * @return alumno
	 */
	public Alumno getAlumno() {
		return this.alumno;
	}

	/**
	 * Set the nombreasig.
	 * 
	 * @param nombreasig
	 *            nombreasig
	 */
	public void setNombreasig(String nombreasig) {
		this.nombreasig = nombreasig;
	}

	/**
	 * Get the nombreasig.
	 * 
	 * @return nombreasig
	 */
	public String getNombreasig() {
		return this.nombreasig;
	}

	/**
	 * Set the nota.
	 * 
	 * @param nota
	 *            nota
	 */
	public void setNota(Float nota) {
		this.nota = nota;
	}

	/**
	 * Get the nota.
	 * 
	 * @return nota
	 */
	public Float getNota() {
		return this.nota;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idnota == null) ? 0 : idnota.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Notas other = (Notas) obj;
		if (idnota == null) {
			if (other.idnota != null) {
				return false;
			}
		} else if (!idnota.equals(other.idnota)) {
			return false;
		}
		return true;
	}

}
